name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint: ubuntu-latest
  name: Lint
  steps:
    - name: Check out source repository
      user: actions.checkout@v3
    - name: Set up Python environmont
      user: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: flake8 Lint
      uses: py-actions/flake8@v2 